# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae5b2d07a0b3c440d148a2bd6b892a1be2ac72d4d8935ee5fcf052b170a526a5da0afe01e6fcefcf7429c2c8a00140f2dec6545a4b73dd9dcc1a60606b8ed977

test:
  secret_key_base: c818a1713133ceeea7ed000c0f2eb2e5c6ecb58a229d066fedfa3380a60e514f79426f0893f82990eaee1c5c067aef97f22a03eba142a415d38c5443a99fcae2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
